#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.6.8 on Wed Sep  2 21:24:17 2015
#

import wx

# begin wxGlade: dependencies
import gettext
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MyFrame(wx.Frame):
  def __init__(self, *args, **kwds):  
    kwds["style"] = wx.DEFAULT_FRAME_STYLE
    wx.Frame.__init__(self, *args, **kwds)

  def create(self, levels, entities):
    # begin wxGlade: MyFrame.__init__
    self.combo_box = set()
    self.label = set()
    for entity in entities:
      self.label.add(wx.StaticText(self, wx.ID_ANY, _(entity)))
      self.combo_box.add(wx.ComboBox(self, wx.ID_ANY, choices=[(_( level)) for level in levels], style=wx.CB_DROPDOWN))

    self.button_1 = wx.Button(self, wx.ID_ANY, _("Run"))
#    self.button_1.Bind(wx.EVT_BUTTON, self.OnClose)
    self.button_2 = wx.Button(self, wx.ID_ANY, _("Close"))
    self.button_2.Bind(wx.EVT_BUTTON, self.OnClose)
    self.__set_properties()
    self.__do_layout()
    # end wxGlade

  def __set_properties(self):
    # begin wxGlade: MyFrame.__set_properties
    self.SetTitle(_("Didfail"))
    # end wxGlade

  def OnClose(self, event):
    dlg = wx.MessageDialog(self, "Do you really want to close this application?","Confirm Exit", wx.OK|wx.CANCEL|wx.ICON_QUESTION)
    result = dlg.ShowModal()
    dlg.Destroy()
    if result == wx.ID_OK:
      self.Destroy()

  def __do_layout(self):
    # begin wxGlade: MyFrame.__do_layout
    sizer_1 = wx.BoxSizer(wx.VERTICAL)
    sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
    sizer_4 = wx.BoxSizer(wx.VERTICAL)
    sizer_5 = wx.BoxSizer(wx.HORIZONTAL)
    sizer_3 = wx.BoxSizer(wx.VERTICAL)

    for label in self.label:
      sizer_3.Add(label, 0, 0, 0)
    for cb in self.combo_box:
      sizer_4.Add(cb, 0, 0, 0)

    sizer_2.Add(sizer_3, 1, wx.EXPAND, 0)
    sizer_5.Add(self.button_1, 0, 0, 0)
    sizer_5.Add(self.button_2, 0, 0, 0)
    sizer_4.Add(sizer_5, 1, wx.EXPAND, 0)
    sizer_2.Add(sizer_4, 1, wx.EXPAND, 0)
    sizer_1.Add(sizer_2, 1, wx.EXPAND, 0)
    self.SetSizer(sizer_1)
    sizer_1.Fit(self)
    self.Layout()
    # end wxGlade

# end of class MyFrame
class MyApp(wx.App):
  def OnInit(self):
    wx.InitAllImageHandlers()
    frame_1 = MyFrame(None, wx.ID_ANY, "")
    self.SetTopWindow(frame_1)
    frame_1.Show()
    return 1

# end of class MyApp

# end of class Main_frame
if __name__ == "__main__":
  gettext.install("app") # replace with the appropriate catalog name

  app = wx.PySimpleApp(0)
  wx.InitAllImageHandlers()
  frame_1 = MyFrame(None, wx.ID_ANY, "")
  frame_1.create(["Private", "Public"], ["send","location"])
  app.SetTopWindow(frame_1)
  frame_1.Show()
  app.MainLoop()